### ISSUE TITLE
Gradle batch/binaries missing

### ISSUE THREAD

**Issue by akarnokd** [meddle0x53/learning-rxjava#1]
Hello. The README.md indicates how to run the demo:

```
gradle rxrun
```

but there is no `gradle`, `gradlew.bat` or `gradle/wrapper/gradle-wrapper.jar` in the repository.

**Comment by meddle0x53** [comment]
Yeah, but it says to install Gradle...

But I'll add the wrapper ASAP.

**Comment by meddle0x53** [comment]
Added it to the project.

**Comment by akarnokd** [comment]
Thanks. It works.
