### ISSUE TITLE
Example one.ReactiveSumExample doesn't work

### ISSUE THREAD

**Issue by akarnokd** [meddle0x53/learning-rxjava#2]
I've tried running it directly and from Runner, but no matter what numbers I type in, there is no output; i.e.,

```
a=1
b=2
```

Only `exit` works somewhat by printing a long stacktrace.

**Comment by meddle0x53** [comment]
This is strange, just today, I've run it. Do you run it from the current master?

**Comment by akarnokd** [comment]
Yes. An hour ago, [this commit](https://github.com/meddle0x53/learning-rxjava/commit/f8f9f820c814b903379596e23acf1530b3bdd457) was the master.

Correction: I did a clean checkout and the example works through the runner, but not standalone (i.e., adding a main method and invoking run()).

**Comment by meddle0x53** [comment]
You are right, I've never run it that way...
But I looked through your fork of the project, and you are right, the input should run on the Schedulers.io() scheduler, but I think the consumers should decide that, not the factory method.

So now the ReactiveSum example is using it with the the IO Scheduler and it will work with a main method like this:

```

    public static void main(String[] args) throws InterruptedException {
        CountDownLatch latch = new CountDownLatch(1);
        new ReactiveSumV1().run();

        CreateObservable.input()
        .subscribeOn(Schedulers.io())
        .filter(line -> line.equals("return"))
        .subscribe(v -> latch.countDown());

        latch.await();
    }
```

**Comment by meddle0x53** [comment]
I don't want to talk about Threading and Schedulers in the first examples, the book should be readable for audience at junior level too... But you are right for everything.
The examples should be simple enough in the book, but a bit more complex in the java files - let's give opportunity to the readers to play.
And some Helper/Utility methods can be the real deal - implemented with unsubscribing and back-pressure in mind.

Btw, do you think this system with the command line application and the runner is a good choice?

**Comment by akarnokd** [comment]
I think standalone runnable examples would be better; I'd expect each example to be runnable from IDE directly. I can't remember when I saw such command-line menu based solution, but feels a bit too old-school to me. In addition, while we are at it, naming the package-chapters as `chapter01` would make it display in-order and allow better discovery.

**Comment by meddle0x53** [comment]
Yeah, such a naming convention would be better, additionally I'll add a main method to every example.

**Comment by akarnokd** [comment]
Thanks. The chapter01 examples now work for me.
