### ISSUE TITLE
/src/test/resources missing

### ISSUE THREAD

**Issue by akarnokd** [meddle0x53/learning-rxjava#3]
Eclipse's [classpath file](https://github.com/meddle0x53/learning-rxjava/blob/master/.classpath#L6) `.classpath` references the missing `/src/test/resources` directory. I'd rather remove `.classpath` and `.project` files (and add them to `.gitignore`) and let Eclipse's Gradle plugin create them on import.

**Comment by meddle0x53** [comment]
Done.
