### ISSUE TITLE
Question: chapter 2 in book and in examples

### ISSUE THREAD

**Issue by akarnokd** [meddle0x53/learning-rxjava#4]
In the review copy, I received chapter 2 which isn't about lambdas but the [code examples](https://github.com/meddle0x53/learning-rxjava/tree/master/src/main/java/com/packtpub/reactive/chapter02) are. Was there a change of outline or chapter ordering?

**Comment by meddle0x53** [comment]
There is a part of chapter 2 about lambdas - it introduces the new java8 syntax and creating lambdas/referencing methods. In the draft file, this content is in pages 2-13.

**Comment by akarnokd** [comment]
What I received starts like this: 

```
2 
Why Observables? 

In this chapter, we are going to have an overview on the  Observer pattern, 
how it’s implemented and extended by RxJava, what an Observable  is, how Observables 
relate to Iterables.
```

**Comment by meddle0x53** [comment]
That sounds more like one of the sections of chapter 01, and it is not chapter 02, the outline I sent and they approved doesn't include anything like that in chapter 02...

**Comment by akarnokd** [comment]
It talks about Subjects, hot and cold Observables, and has examples such as this:

``` java
List<Integer> items = new ArrayList<Integer>();
items.add(1);
items.add(10);
items.add(100);
items.add(200);

Observable<Integer> observableString = Observable.from(items);

Subscription subscriptionPrint = observableString.subscribe(new Observer<Integer>() {
    @Override
    public void onCompleted() {
        System.out.println("Observable completed");
    }

    @Override
    public void onError(Throwable e) {
        System.out.println("Oh no! Something wrong happened!");
    }

    @Override
    public void onNext(Integer item) {
        System.out.println("Item is " + item);
    }
});
```

This I haven't found among the examples of this repository, so I'm confused. Feels like it is partially what's chapter 3 might be:

> Chapter 3: Creating And Connecting Observables, Observers And Subjects – 15-20 pages
> Description
> We will get to know the basic building blocks of the RxJava library – we'll create RxJava Observables and Subscribers and interact with them; we'll introduce many of the Observable factory methods like 'from', 'just', 'empty'; we'll talk about 'hot' and 'cold' observables, 'blocking' and 'non-blocking' observables, 'connectable' observables and we'll subscribe to them. We will subscribe to these observables and unsubscribe from them, using a Subscription instance. At the end of the chapter, we'll play with and chain various Subject instances.

Are there other authors to the book or is the publisher restructuring the manuscript on their own?

**Comment by meddle0x53** [comment]
I'm the sole author - and this is chapter 03.

I guess they got it wrong, or they are editing it in some very strange way...

**Comment by akarnokd** [comment]
I assume you sent your chapter 2 about lambdas to the publisher before chapter 3, right?

**Comment by meddle0x53** [comment]
Yeah... in the beginning of the month... Maybe we should talk about these things in private...
My skype is meddle053h, and google - n.tzvetinov@gmail.com.

**Comment by akarnokd** [comment]
Okay. Sent you a chat invitation via Google.
